name: Check Broken Links

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1" # At 03:00 UTC on Monday: https://crontab.guru/#0_3_*_*_1

permissions:
  contents: write

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23
      - name: Build app
        run: |
          go mod download
          make build
      - name: "Check Links: hazadus.ru"
        run: |
          today=$(date +"%Y-%m-%d") && \
          mkdir -p ./reports && \
          ./bin/broken && \
          mv ./report.md "./reports/hazadus.ru.$today.md"
      - name: "Check Links: speakers24.ru"
        run: |
          today=$(date +"%Y-%m-%d") && \
          mkdir -p ./reports && \
          ./bin/broken -s "https://speakers24.ru" -d "speakers24.ru" -i "https://speakers24.ru,https://www.speakers24.ru,https://спикеры24.ру" && \
          mv ./report.md "./reports/speakers24.ru.$today.md"
      - name: "Check Links: anvlink.ru"
        run: |
          today=$(date +"%Y-%m-%d") && \
          mkdir -p ./reports && \
          ./bin/broken -s "https://anvlink.ru" -d "anvlink.ru" -i "https://anvlink.ru,https://anvl.ink" && \
          mv ./report.md "./reports/anvlink.ru.$today.md"
      - name: "Check Links: nameapp.anverali.tech"
        run: |
          today=$(date +"%Y-%m-%d") && \
          mkdir -p ./reports && \
          ./bin/broken -s "https://nameapp.anverali.tech" -d "nameapp.anverali.tech" -i "https://nameapp.anverali.tech" && \
          mv ./report.md "./reports/nameapp.$today.md"
      - name: Commit and push
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Отчёт от ${timestamp}" || exit 0
          git pull --rebase
          git push
